/**
 * Version information for the compiled script
 * This file is automatically updated before each build.
 *
 * Auto-generated by the version bump script (triggered by `npm run push`).
 * Do not edit manually. See src/scripts/update-version.cjs for the generator.
 */

const versionData = {
  "version": "2.0.0+3dfd999",
  "commit": "3dfd999",
  "branch": "pr28",
  "isDirty": true,
  "buildDate": "2026-05-11T10:22:06.421Z"
};

export function getVersionInfo(): string {
  const dirty = versionData.isDirty ? ' (dirty)' : '';
  return `${versionData.version}${dirty} (${versionData.commit} on ${versionData.branch})`;
}

export function getFullVersionInfo(): string {
  return `Compiled using ${versionData.version} at ${versionData.buildDate}`;
}

export const VERSION = versionData.version;
export const COMMIT = versionData.commit;
export const BRANCH = versionData.branch;
