/**
 * Version information for the compiled script
 * This file is automatically updated before each build.
 *
 * Auto-generated by the version bump script (triggered by `npm run push`).
 * Do not edit manually. See src/scripts/update-version.cjs for the generator.
 */

const versionData = {
  "version": "2.0.0+c8e4510",
  "commit": "c8e4510",
  "branch": "refactor/34-split-lint-modules",
  "isDirty": true,
  "buildDate": "2026-06-28T18:32:40.459Z"
};

export function getVersionInfo(): string {
  const dirty = versionData.isDirty ? ' (dirty)' : '';
  return `${versionData.version}${dirty} (${versionData.commit} on ${versionData.branch})`;
}

export function getFullVersionInfo(): string {
  return `Compiled using ${versionData.version} at ${versionData.buildDate}`;
}

export const VERSION = versionData.version;
export const COMMIT = versionData.commit;
export const BRANCH = versionData.branch;
