/**
 * Version information for the compiled script
 * This file is automatically updated before each build.
 *
 * Auto-generated by the version bump script (triggered by `npm run push`).
 * Do not edit manually. See src/scripts/update-version.cjs for the generator.
 */

const versionData = {
  "version": "2.0.0+0f61d3f",
  "commit": "0f61d3f",
  "branch": "fix/unicode-option-values-and-lint-fixes",
  "isDirty": false,
  "buildDate": "2026-07-23T10:29:09.943Z"
};

export function getVersionInfo(): string {
  const dirty = versionData.isDirty ? ' (dirty)' : '';
  return `${versionData.version}${dirty} (${versionData.commit} on ${versionData.branch})`;
}

export function getFullVersionInfo(): string {
  return `Compiled using ${versionData.version} at ${versionData.buildDate}`;
}

export const VERSION = versionData.version;
export const COMMIT = versionData.commit;
export const BRANCH = versionData.branch;
